app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => 'web'], function () {

	// Welcome routes
	Route::get('/', 'WelcomeController@index');
	

    // Auth routes
    Route::auth();
    

    // Home Routes
    Route::get('/home', 'HomeController@index')->name('home');


    // Admin routes
	Route::group(['prefix' => 'admin'], function () {

		// administration welcome
		Route::get('/', 'AdministratorController@index')->name('admin');


		// restful controllers
		Route::post('managers/bulk-destroy', 'Modules\Admin\ManagerController@bulkDestroy')->name('managers.bulkdestroy');
		Route::resource('managers', 'Modules\Admin\ManagerController');

		Route::post('members/bulk-destroy', 'Modules\Admin\MemberController@bulkDestroy')->name('members.bulkdestroy');
		Route::resource('members', 'Modules\Admin\MemberController');


		// change password route (only for admins)
		Route::get('/change-password', 'AdministratorController@get_change_password')->name('get.changepassword');
		Route::post('/change-password', 'AdministratorController@post_change_password')->name('post.changepassword');

	});

});

app/Models/Member.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Member extends Model
{
	protected $guarded = [
		'id'
	];

	public function user()
	{
		return $this->belongsTo('App\Models\User');
	}
}

app/Http/Controllers/Modules/Admin/ManagerController.php
<?php

namespace App\Http\Controllers\Modules\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Repositories\ManagerRepository;
use Spatie\Permission\Models\Permission;

class ManagerController extends Controller
{
    private $managers;

    public function __construct( ManagerRepository $managers)
    {
        $this->managers = $managers;
    }

    public function bulkDestroy()
    {
        $ids = request()->input('manager_ids');

        foreach($ids as $id)
        {   
            $this->managers->delete($id);
        }

        return redirect()->route('admin.managers.index')
                    ->with('global_success', 'El/los administrador(es) fue(ron) eliminado(s) con éxito.');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $managers = $this->managers->findAll();

        return view( 'modules.managers.index', compact('managers') );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $mode = 'create';

        $roles = Permission::where('name','!=','de_member')->get();

        return view('modules.managers.form', compact(
            'mode',
            'roles'
        ));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate(request(), [
            'first_name' => 'required',
            'middle_name' => 'required',
            'last_name' => 'required',
            'email' => 'required|email|unique:users',
            'roles' => 'required'
        ]);

        $roles = request()->input('roles');

        $data = array_except(request()->all(), ['_method', '_token', 'roles']);

        list($manager, $managerPassword) = $this->managers->store($data, $roles);

        return redirect()->route('admin.managers.index')
                        ->with('global_success', "El administrador ha sido creado con éxito.<br>La constraseña de este usuario es: <b>".$managerPassword."</b>");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $manager = $this->managers->find($id);

        $mode = "edit";

        $roles = Permission::where('name','!=','de_member')->get();

        return view('modules.managers.form', compact(
            'roles',
            'mode',
            'manager'
        ));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $manager = $this->managers->find($id);

        $this->validate(request(), [
            'first_name' => 'required',
            'middle_name' => 'required',
            'last_name' => 'required',
            'email' => 'required|email|unique:users,email,'.$manager->user->id,
            'roles' => 'required'
        ]);

        $roles = request()->input('roles');

        $data = array_except(request()->all(), ['_method', '_token', 'roles']);

        $manager = $this->managers->update($id, $data, $roles);

        return redirect()->route('admin.managers.index')
                        ->with('global_success', 'El administrador ha sido actualizado con éxito.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->managers->delete($id);

        return redirect()->route('admin.managers.index')
                    ->with('global_success', 'El administrador ha sido eliminado con éxito.');
    }
}

app/Http/Controllers/Modules/Admin/MemberController.php
<?php

namespace App\Http\Controllers\Modules\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Repositories\MemberRepository;
use DB;

class MemberController extends Controller
{
    private $members;

    public function __construct(MemberRepository $members)
    {
        $this->members = $members;
    }

    public function bulkDestroy()
    {
        $ids = request()->input('members_ids');

        foreach($ids as $id)
        {   
            $this->members->delete($id);
        }

        return redirect()->route('admin.members.index')
                    ->with('global_success', 'El/los miembro(s) fue(ron) eliminado(s) con éxito.');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $members = $this->members->findAll();

        return view( 'modules.members.index', compact('members') );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $mode = 'create';

        return view( 'modules.members.form', compact('mode') );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = array_except(request()->all(), ['_token']);

        $manager = $this->members->store( $data );

        return redirect()->route('admin.members.index')
                        ->with('global_success', 'El miembro ha sido creado con éxito.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $member = $this->members->find($id);

        $mode = "edit";

        return view('modules.members.form', compact(
            'mode',
            'member'
        ));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = array_except(request()->all(), ['_token']);

        $manager = $this->members->update($id, $data);

        return redirect()->route('admin.members.index')
                        ->with('global_success', 'El miembro ha sido actualizado con éxito.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->members->delete($id);

        return redirect()->route('admin.members.index')
                    ->with('global_success', 'El miembro ha sido eliminado con éxito.'); 
    }
}

app/Http/Controllers/Modules/Frontend/ManagerController.php
<?php

namespace App\Http\Controllers\Modules\Frontend;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class ManagerController extends Controller
{
    //
}

app/Http/Controllers/Modules/Frontend/MemberController.php
<?php

namespace App\Http\Controllers\Modules\Frontend;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class MemberController extends Controller
{
    //
}

resources/views/modules/members/index.blade.php
@extends('layouts.admin')

@section('scripts')
    @parent
    <script>

        $(document).ready(function() {

            $('#example').DataTable(
            {
                ordering:false
            });


            $('#members-link').addClass('active');


            $('#check-all').click(function() 
            {
                var boolSetting = false;

                if( $(this).prop('checked') )
                {
                    boolSetting = true;
                }

                $('tbody input[type=checkbox]').each(function(index,element) {

                    $(this).prop('checked', boolSetting);

                });

            });


            $('#delete-bulk-action').click(function() 
            {
                if( $('tbody input[type=checkbox]:checked').length <= 0 )
                {
                    alert('No has seleccionado a nadie para eliminar.');
                    return;
                }

                if( confirm('Está seguro de eliminar a el/los administrador(es)?') )
                {
                    document.forms['deleteBulkForm'].submit();
                }
            });

        });

    </script>
@endsection


@section('content')
    
    @include('partials.messages')

    <div class="container">
    	<div class="row">
    		<div class="col-md-10 col-md-offset-1">
    				
    			<div class="page-header">
    				<h1>Miembros</h1>
    			</div>

                <br>

                <div>
                    <a href="{{ route('admin.members.create') }}" class="btn btn-default"><i class="fa fa-plus"></i> Crear miembro</a>
                    <button id="delete-bulk-action" class="btn btn-danger"> <i class="fa fa-trash" aria-hidden="true"></i></button>
                </div>
                <br>

                <form name="deleteBulkForm" action="{{ route('members.bulkdestroy') }}" method="post">
                    {!! csrf_field() !!}

                    <div class="table-responsive">
                    	<table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>
                                        <div class="checkbox">
                                            <label>
                                                All
                                                <input id="check-all" type="checkbox">
                                            </label>
                                        </div>
                                    </th>
                                    <th>Nombre(s)</th>
                                    <th>Ape. Paterno</th>
                                    <th>Ape. Materno</th>
                                    <th>Sector</th>
                                </tr>
                            </thead>
                            <tbody>

                                @forelse($members as $member)
                                    <tr>
                                        <td>
                                            <div class="checkbox">
                                                <input name="members_ids[]" type="checkbox" value="{{ $member->id }}">
                                            </div>
                                        </td>
                                        <td><a href="{{ route('admin.members.edit', [$member->id]) }}">{{ $member->user->first_name }}</a></td>
                                        <td>{{ $member->user->middle_name }}</td>
                                        <td>{{ $member->user->last_name }}</td>
                                        <td>{{ $member->sector }}</td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="5">No existen miembros por el momento.</td>
                                    </tr>
                                @endforelse
                                
                            </tbody>
                        </table>
                    </div>

                </form>

    		</div>
    	</div>
    </div>
@endsection