app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => 'web'], function () {

	// Welcome routes
	Route::get('/', 'WelcomeController@index');
	

    // Auth routes
    Route::auth();
    

    // Home Routes
    Route::get('/home', 'HomeController@index')->name('home');


    // Admin routes
	Route::group(['prefix' => 'admin'], function () {

		// administration welcome
		Route::get('/', 'AdministratorController@index')->name('admin');


		// restful controllers
		Route::post('managers/bulk-destroy', 'Modules\Admin\ManagerController@bulkDestroy')->name('managers.bulkdestroy');
		Route::resource('managers', 'Modules\Admin\ManagerController');

		Route::post('members/bulk-destroy', 'Modules\Admin\MemberController@bulkDestroy')->name('members.bulkdestroy');
		Route::resource('members', 'Modules\Admin\MemberController');


		// change password route (only for admins)
		Route::get('/change-password', 'AdministratorController@get_change_password')->name('get.changepassword');
		Route::post('/change-password', 'AdministratorController@post_change_password')->name('post.changepassword');

	});

});

resources/views/layouts/admin.blade.php
@extends('layouts.app')


@section('styles')
	<link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.6/united/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" href="https://cdn.datatables.net/1.10.11/css/dataTables.bootstrap.min.css">
@endsection


@section('scripts')
	@parent
	<script src="https://cdn.datatables.net/1.10.11/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.11/js/dataTables.bootstrap.min.js"></script>
@endsection


@section('leftside-nav')

    @if( Auth::user()->isAdmin() )
        <li id="managers-link"><a href="{{ route('admin.managers.index') }}">Administradores</a></li>
        <li id="members-link"><a href="{{ route('admin.members.index') }}">Miembros</a></li>
    @endif
        
@endsection


@section('rightside-nav')
    <li><a href="{{ route('get.changepassword') }}"><i class="fa fa-btn fa-key"></i>Cambiar contraseña</a></li>
    @parent
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Directorio Sifme</title>

    <!-- Fonts -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel='stylesheet' type='text/css'>

    <!-- Styles -->
    @section('styles')
        <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.6/flatly/bootstrap.min.css" rel="stylesheet">
    @show

    <style>

        html {
            height: 100%;
        }

        body {
            padding-bottom: 100px;
        }

        .fa-btn {
            margin-right: 6px;
        }

    </style>

</head>
<body>

    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    Directorio Sifme
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">

                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav navbar-left">

                    @section('leftside-nav')

                        @if( Auth::check() )
                            <li><a href="#">Ver cursos</a></li>
                            <li><a href="#">Donaciones</a></li>
                        @endif

                    @show
                    
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (! Auth::check())
                        <li><a href="{{ url('/login') }}">Login</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->fullname() }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                @section('rightside-nav')
                                    <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                                @show
                            </ul>
                        </li>
                    @endif

                </ul>

            </div>

        </div>
    </nav>

    @yield('content')

    <!-- JavaScripts -->
    @section('scripts')
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    @show
</body>
</html>